Initial implementation
kaey/ctxlog pull request #1
Opened 2018-01-16 13:14 UTC by kaey

2018-01-17 10:05 UTC, bikbah commented on log.go
> +	OrigMsg string `json:"orig-msg"`
`-` или `_`?

2018-01-17 13:13 UTC, Stepych requested changes

2018-01-17 13:13 UTC, Stepych commented on log.go
> +	atomic.StoreInt32(l.debug, 0)
Надо перенести в `else`, а то всегда будет `0`.

2018-01-17 13:13 UTC, Stepych commented on log.go
> +	now := time.Now().UTC().Format(time.RFC3339Nano)
Не очень красиво получается дублирование этой строчки повсюду. Понятно, что сделано ради упрощения тестов, но все же читалось бы лучше отсутствие параметра `timeStr` у `print()`.

2018-01-18 09:57 UTC, kaey commented on log.go
> +	now := time.Now().UTC().Format(time.RFC3339Nano)
не вижу смысла усложнять тесты чтобы убрать одну строчку из 3 функций

2018-02-04 20:11 UTC, Stepych approved these changes

2018-06-21 13:00 UTC, merged